#  Name of workflow
name: Lint workflow
# Trigger workflow on all pull requests
on:
    pull_request:
        branches:
            - dev
            - main
# Jobs to carry out
jobs:
    test:
        runs-on: ubuntu-latest
        steps:          
            - name: Checkout code
            uses: actions/checkout@v1            
            - name: Use Node.js 12.x
            uses: actions/setup-node@v1
            with:
                node-version: 12.x
            - name: 🧰 install deps
            run: npm install
            - name: Run lint
            run: npm run lint